### ISSUE TITLE
Unprovided export error with Vite SSR

### ISSUE THREAD

**Issue by knpwrs** [solidjs/solid#1040]
### Describe the bug

When attempting to use `solid-app-router` with vite's SSR mode, vite complains that `solid-js/web` doesn't have an export named `effect`. Indeed, there are only two export statements from the `solid-js/web` es module and neither of them contain `effect`:

```ts
export { ErrorBoundary, For, Index, Match, Show, Suspense, SuspenseList, Switch, createComponent, mergeProps } from 'solid-js';
// ...
export { Assets, Dynamic, HydrationScript, NoHydration, Portal, escape, generateHydrationScript, getHydrationKey, isServer, pipeToNodeWritable, pipeToWritable, renderToStream, renderToString, renderToStringAsync, resolveSSRNode, spread, ssr, ssrAttribute, ssrClassList, ssrHydrationKey, ssrSpread, ssrStyle };
```

I wasn't sure if I should open this bug here so that `solid-js/web` could export `effect` or if I should open over at `solid-app-router` so it could grab the export from a different location.

### Your Example Website or App

https://github.com/fastify/fastify-vite/tree/967be02cd66539b3cf70dc9df59b5c0af2c0f853/examples/solid-hydration

### Steps to Reproduce the Bug or Issue

1. Attempt to run example provided
2. Get the following error:

```
> NODE_ENV=development ts-node server.ts

3:04:21 PM [vite] Error when evaluating SSR module /base.tsx:
file:///Users/knpwrs/Workspace/squircle/squircle-solid-exp/node_modules/solid-app-router/dist/index.js:1
import { isServer, template, createComponent as createComponent$1, mergeProps, spread, insert, effect, setAttribute } from 'solid-js/web';
                                                                                               ^^^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'effect'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:435:15)
    at async nodeImport (/Users/knpwrs/Workspace/squircle/squircle-solid-exp/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:59403:21)
    at async eval (/base.tsx:7:31)
    at async instantiateModule (/Users/knpwrs/Workspace/squircle/squircle-solid-exp/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:59333:9)
3:04:21 PM [vite] Error when evaluating SSR module /Users/knpwrs/Workspace/squircle/squircle-solid-exp/client/index.ts:
file:///Users/knpwrs/Workspace/squircle/squircle-solid-exp/node_modules/solid-app-router/dist/index.js:1
import { isServer, template, createComponent as createComponent$1, mergeProps, spread, insert, effect, setAttribute } from 'solid-js/web';
                                                                                               ^^^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'effect'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:435:15)
    at async nodeImport (/Users/knpwrs/Workspace/squircle/squircle-solid-exp/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:59403:21)
    at async eval (/base.tsx:7:31)
    at async instantiateModule (/Users/knpwrs/Workspace/squircle/squircle-solid-exp/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:59333:9)
file:///Users/knpwrs/Workspace/squircle/squircle-solid-exp/node_modules/solid-app-router/dist/index.js:1
import { isServer, template, createComponent as createComponent$1, mergeProps, spread, insert, effect, setAttribute } from 'solid-js/web';
                                                                                               ^^^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'effect'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:435:15)
    at async nodeImport (/Users/knpwrs/Workspace/squircle/squircle-solid-exp/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:59403:21)
    at async eval (/base.tsx:7:31)
    at async instantiateModule (/Users/knpwrs/Workspace/squircle/squircle-solid-exp/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:59333:9)
zsh: exit 1     npm run dev
```

### Expected behavior

`solid-app-router` should only import things from `solid-js/web` that actually exist.

### Platform

- OS: macOS
- Browser: n/a
- Version: 1.4.3

**Comment by ryansolid** [comment]
This is mostly likely the client build getting pulled in on the server. We havent' found a great solve here other than basically adding all Solid libraries that use JSX  to `ssr.noExternal` in the Vite config. I know Svelte has been working on similar issues. At one point they hardcoded every known library, not sure if they found a better solve.

**Comment by galvez** [comment]
I'm unable to reproduce, [the example](https://github.com/fastify/fastify-vite/tree/dev/examples/solid-hydration) boots and runs fine for me.

<img width="1086" alt="Screen Shot 2022-06-04 at 17 26 51" src="https://user-images.githubusercontent.com/12291/172024561-658e7d72-5efe-440a-9e4a-e5600d6d6524.png">

**Comment by galvez** [comment]
Indeed, I have [`noExternal` set for `solid-app-router`](https://github.com/fastify/fastify-vite/blob/dev/examples/solid-hydration/vite.config.js) in this example as well.

**Comment by galvez** [comment]
@ryansolid Maybe the Solid Vite plugin could automatically make this setting given `solid-app-router` is an official package?

**Comment by ryansolid** [comment]
That's what I meant by hardcoding. It seems like a poor solution since literally every library needs to do this. We need a smarter solution here. Just not sure how to do it.
