### ISSUE TITLE
CSS Animations example doesn't work

### ISSUE THREAD

**Issue by caburj** [solidjs/solid#1218]
### Describe the bug

Navigate to the CSS Animations example and it won't render anything because it crashes with the following error:

```
eruda:8 Console was cleared
eruda:8 TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at getRect (solid-transition-group.js:126:41)
    at solid-transition-group.js:236:16
    at Array.forEach (<anonymous>)
    at Object.fn (solid-transition-group.js:232:7)
    at runComputation (solid-67d434a6.js:675:22)
    at updateComputation (solid-67d434a6.js:660:3)
    at createEffect (solid-67d434a6.js:206:31)
    at TransitionGroup (solid-transition-group.js:230:3)
    at solid-bbf2753b.js:1218:24
    at untrack (solid-bbf2753b.js:430:12)
Ma.forEach.n.<computed> @ eruda:8
(anonymous) @ 3904e498-42ba-437f-91f6-03a6b5951937:107
postMessage (async)
(anonymous) @ setupRepl.d213c771.js:783
aa @ index.a63cbc0b.js:1
bt @ index.a63cbc0b.js:1
Xt @ index.a63cbc0b.js:1
ur @ index.a63cbc0b.js:1
(anonymous) @ index.a63cbc0b.js:1
ve @ index.a63cbc0b.js:1
dr @ index.a63cbc0b.js:1
ve @ index.a63cbc0b.js:1
Qa @ index.a63cbc0b.js:1
o @ index.a63cbc0b.js:1
(anonymous) @ setupRepl.d213c771.js:6750
```

### Your Example Website or App

https://www.solidjs.com/examples/cssanimations

### Steps to Reproduce the Bug or Issue

Check out this 45-sec video: https://youtu.be/d1Jk8Ma58iQ

### Expected behavior

I expected to see some transitions and animations.

### Platform

- OS: macOS 12.5.1 (M1)
- Browser: Safari Version 15.6.1, Google Chrome Version 105.0.5195.102

**Comment by ryansolid** [comment]
Hmm.. the example works in codesandbox: https://codesandbox.io/s/basic-css-transition-36rln

So probably something specific to playground/website. I will transfer the issue there.
