### ISSUE TITLE
Error on Todos example

### ISSUE THREAD

**Issue by MiloslavStekrt** [solidjs/solid#1219]
### Describe the bug

https://www.solidjs.com/examples/todos

On this website specificly pressing add in **playground** prints error

```
Console was cleared
Cannot read properties of undefined (reading 'title')
at setProperty (https://cdn.skypack.dev/-/solid-js@v1.5.4-FMTpIuHGAWtYn2lofUNf/dist=es2019,mode=imports/optimized/solid-js/store.js:138:25)
at mergeStoreNode (https://cdn.skypack.dev/-/solid-js@v1.5.4-FMTpIuHGAWtYn2lofUNf/dist=es2019,mode=imports/optimized/solid-js/store.js:157:5)
at updatePath (https://cdn.skypack.dev/-/solid-js@v1.5.4-FMTpIuHGAWtYn2lofUNf/dist=es2019,mode=imports/optimized/solid-js/store.js:220:5)
at https://cdn.skypack.dev/-/solid-js@v1.5.4-FMTpIuHGAWtYn2lofUNf/dist=es2019,mode=imports/optimized/solid-js/store.js:230:77
at runUpdates (https://cdn.skypack.dev/-/solid-js@v1.5.4-FMTpIuHGAWtYn2lofUNf/dist=es2019,mode=imports/optimized/common/solid-bbf2753b.js:775:12)
at batch (https://cdn.skypack.dev/-/solid-js@v1.5.4-FMTpIuHGAWtYn2lofUNf/dist=es2019,mode=imports/optimized/common/solid-bbf2753b.js:425:10)
at setStore (https://cdn.skypack.dev/-/solid-js@v1.5.4-FMTpIuHGAWtYn2lofUNf/dist=es2019,mode=imports/optimized/solid-js/store.js:229:5)
at blob:https://www.solidjs.com/416b3e0f-8e6f-4612-8a2a-4329b933e1c9:26:7
at runUpdates (https://cdn.skypack.dev/-/solid-js@v1.5.4-FMTpIuHGAWtYn2lofUNf/dist=es2019,mode=imports/optimized/common/solid-bbf2753b.js:785:17)
at batch (https://cdn.skypack.dev/-/solid-js@v1.5.4-FMTpIuHGAWtYn2lofUNf/dist=es2019,mode=imports/optimized/common/solid-bbf2753b.js:425:10)
```

### Your Example Website or App

https://www.solidjs.com/examples/todos

### Steps to Reproduce the Bug or Issue

1. open https://www.solidjs.com/examples url in new tab
2. open simple todos example
3. start playground
4. type text into the input
5. press plus symbol / button for submit the form
6. see the code below

### Expected behavior

Expecting program to add todo to list of todos. No errors.

### Screenshots or Videos

![2022-09-11_21-44](https://user-images.githubusercontent.com/59827867/189548535-471e889b-d068-4a33-9fb7-8a7bcc8de288.png)

### Platform

- OS: Arch Linux
- Browser: Chromium / Brave
- Version: [Version 1.42.95 Chromium: 104.0.5112.81 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by ryansolid** [comment]
This I believe is caused by having older versions of this demo saved in your localstorage as this demo saves in local storage.

You can see the fully working one here (assuming you haven't visited this link before): https://codesandbox.io/s/lrm786ojqz?file=/index.tsx

Easiest way to fix this is type localStorage.clear(); in your console when you are on this page.
