### ISSUE TITLE
npx degit:  code: 'BAD_SRC'

### ISSUE THREAD

**Issue by sysmat** [solidjs/solid#1274]
### Describe the bug

- using starting point: https://www.solidjs.com/guides/getting-started
- npx degit solidjs/templates/js my-app
- npx degit solidjs/templates/ts my-app
- both return error:
```
throw new DegitError(`could not parse ${src}`, {
                ^

DegitError: could not parse solidjs\\templates\\js
    at parse (C:\Users\tomaz\AppData\Roaming\npm\node_modules\degit\index.js:392:9)
    at new Degit (C:\Users\tomaz\AppData\Roaming\npm\node_modules\degit\index.js:134:15)
    at degit (C:\Users\tomaz\AppData\Roaming\npm\node_modules\degit\index.js:122:9)
    at Object.<anonymous> (C:\Users\tomaz\AppData\Roaming\npm\node_modules\degit\bin.js:32:12)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'BAD_SRC'
}
```

### Your Example Website or App

no app

### Steps to Reproduce the Bug or Issue

npx degit solidjs/templates/js my-app

### Expected behavior

to create a skeleton app

### Platform

- OS: Windows
- Browser: Chrome
- node: 16.15.1
- npm: 8.18.0
- npx:  8.11.0

**Comment by sysmat** [comment]
if I try for example: `npx degit sveltejs/template my-svelte-project` works fine it create a skeleton app
