### ISSUE TITLE
v1.6.0: Breaks Vite transform with "transformCondition is not defined"

### ISSUE THREAD

**Issue by KevinBLT** [solidjs/solid#1295]
### Describe the bug

I hit into this right today and thought that my changes broke something. 

Unfortunately I only have the stack, which is not pointing anywhere into my code at all, so I have no Idea and will need to hold on 1.5.7: 

```bash
xxxxxxx/node_modules/@solidjs/router/dist/components.jsx: transformCondition is not defined
18:55:12 [vite] Internal server error: xxxxxxx/node_modules/@solidjs/router/dist/components.jsx: transformCondition is not defined
  Plugin: solid
  File: xxxxxxx/node_modules/@solidjs/router/dist/components.jsx
      at xxxxxxx/node_modules/babel-plugin-jsx-dom-expressions/index.js:1463:26
      at Array.forEach (<anonymous>)
      at processSpreads$1 (xxxxxxx/node_modules/babel-plugin-jsx-dom-expressions/index.js:1424:14)
      at transformAttributes$2 (xxxxxxx/node_modules/babel-plugin-jsx-dom-expressions/index.js:760:32)
      at transformElement$3 (xxxxxxx/node_modules/babel-plugin-jsx-dom-expressions/index.js:624:3)
      at transformElement (xxxxxxx/node_modules/babel-plugin-jsx-dom-expressions/index.js:3145:12)
      at transformNode (xxxxxxx/node_modules/babel-plugin-jsx-dom-expressions/index.js:3034:12)
      at PluginPass.transformJSX (xxxxxxx/node_modules/babel-plugin-jsx-dom-expressions/index.js:2995:18)
      at newFn (xxxxxxx/node_modules/@babel/traverse/lib/visitors.js:181:21)
      at NodePath._call (xxxxxxx/node_modules/@babel/traverse/lib/path/context.js:53:20)
      at NodePath.call (xxxxxxx/node_modules/@babel/traverse/lib/path/context.js:40:17)
      at NodePath.visit (xxxxxxx/node_modules/@babel/traverse/lib/path/context.js:100:31)
      at TraversalContext.visitQueue (xxxxxxx/node_modules/@babel/traverse/lib/context.js:105:16)
      at TraversalContext.visitSingle (xxxxxxx/node_modules/@babel/traverse/lib/context.js:79:19)
      at TraversalContext.visit (xxxxxxx/node_modules/@babel/traverse/lib/context.js:133:19)
      at traverseNode (xxxxxxx/node_modules/@babel/traverse/lib/traverse-node.js:24:17)
      at NodePath.visit (xxxxxxx/node_modules/@babel/traverse/lib/path/context.js:107:52)
      at TraversalContext.visitQueue (xxxxxxx/node_modules/@babel/traverse/lib/context.js:105:16)
      at TraversalContext.visitMultiple (xxxxxxx/node_modules/@babel/traverse/lib/context.js:74:17)
      at TraversalContext.visit (xxxxxxx/node_modules/@babel/traverse/lib/context.js:131:19)
      at traverseNode (xxxxxxx/node_modules/@babel/traverse/lib/traverse-node.js:24:17)
      at NodePath.visit (xxxxxxx/node_modules/@babel/traverse/lib/path/context.js:107:52)
      at TraversalContext.visitQueue (xxxxxxx/node_modules/@babel/traverse/lib/context.js:105:16)
      at TraversalContext.visitSingle (xxxxxxx/node_modules/@babel/traverse/lib/context.js:79:19)
      at TraversalContext.visit (xxxxxxx/node_modules/@babel/traverse/lib/context.js:133:19)
      at traverseNode (xxxxxxx/node_modules/@babel/traverse/lib/traverse-node.js:24:17)
      at NodePath.visit (xxxxxxx/node_modules/@babel/traverse/lib/path/context.js:107:52)
      at TraversalContext.visitQueue (xxxxxxx/node_modules/@babel/traverse/lib/context.js:105:16)
      at TraversalContext.visitSingle (xxxxxxx/node_modules/@babel/traverse/lib/context.js:79:19)
      at TraversalContext.visit (xxxxxxx/node_modules/@babel/traverse/lib/context.js:133:19)
      at traverseNode (xxxxxxx/node_modules/@babel/traverse/lib/traverse-node.js:24:17)
      at NodePath.visit (xxxxxxx/node_modules/@babel/traverse/lib/path/context.js:107:52)
      at TraversalContext.visitQueue (xxxxxxx/node_modules/@babel/traverse/lib/context.js:105:16)
      at TraversalContext.visitMultiple (xxxxxxx/node_modules/@babel/traverse/lib/context.js:74:17)
      at TraversalContext.visit (xxxxxxx/node_modules/@babel/traverse/lib/context.js:131:19)
      at traverseNode (xxxxxxx/node_modules/@babel/traverse/lib/traverse-node.js:24:17)
      at NodePath.visit (xxxxxxx/node_modules/@babel/traverse/lib/path/context.js:107:52)
      at TraversalContext.visitQueue (xxxxxxx/node_modules/@babel/traverse/lib/context.js:105:16)
      at TraversalContext.visitSingle (xxxxxxx/node_modules/@babel/traverse/lib/context.js:79:19)
      at TraversalContext.visit (xxxxxxx/node_modules/@babel/traverse/lib/context.js:133:19)
      at traverseNode (xxxxxxx/node_modules/@babel/traverse/lib/traverse-node.js:24:17)
      at traverse (xxxxxxx/node_modules/@babel/traverse/lib/index.js:62:34)
      at transformFile (xxxxxxx/node_modules/@babel/core/lib/transformation/index.js:108:29)
      at transformFile.next (<anonymous>)
      at run (xxxxxxx/node_modules/@babel/core/lib/transformation/index.js:35:12)
      at run.next (<anonymous>)
      at transform (xxxxxxx/node_modules/@babel/core/lib/transform.js:29:41)
      at transform.next (<anonymous>)
      at step (xxxxxxx/node_modules/gensync/index.js:261:32)
      at xxxxxxx/node_modules/gensync/index.js:273:13
```

In the failing code section I was only able to see that there are a lot of calls going to `transformCondition$1` but in this line it's `transformCondition` - which is not defined.

### Your Example Website or App

#Private

### Steps to Reproduce the Bug or Issue

Was just a normal working project, nothing changed.

### Expected behavior

Not causing an error message.

### Platform

- OS: maxOS
- env: Vite / VS Code / dev-server

**Comment by ryansolid** [comment]
Yeah clear your lock and re-install should be fixed. Just missed an import on a code path that was missing a test. To confirm you should have babel-plugin-jsx-dom-expressions 0.35.1
