### ISSUE TITLE
Drawer component not working

### ISSUE THREAD

**Issue by fbedussi** [solidjs/solid#1364]
### Describe the bug

The demo of the Drawer component
https://stackblitz.com/run?file=src%2FApp.tsx

is not working, when I click on a button nothing happens. 

When I copy and paste the sample code in my project, I can see the "left", "right", "top", "bottom" buttons, but when I click one of them I get this error:

dev.js:1269 Uncaught TypeError: Cannot use 'in' operator to search for 'Symbol(solid-proxy)' in true
    at Object.has (dev.js:1269:15)
    at Object.has (dev.js:1236:14)
    at Object.has (dev.js:1269:15)
    at Object.has (dev.js:1236:14)
    at splitProps (dev.js:1303:20)
    at Dynamic (dev.js:571:23)
    at dev.js:516:12
    at untrack (dev.js:421:12)
    at Object.fn (dev.js:512:37)
    at runComputation (dev.js:694:22)

### Your Example Website or App

https://stackblitz.com/run?file=src%2FApp.tsx

### Steps to Reproduce the Bug or Issue

1. Go to https://stackblitz.com/run?file=src%2FApp.tsx
2. click on a button ("left", "right", "top" or "bottom")

### Expected behavior

The drawer opens

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by fbedussi** [comment]
Sorry this is a SUID bug :-)
