### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'Symbol(solid-proxy)' in 10

### ISSUE THREAD

**Issue by adminy** [solidjs/solid#1391]
### Describe the bug

```
dev.js:1259 Uncaught TypeError: Cannot use 'in' operator to search for 'Symbol(solid-proxy)' in 10
    at dev.js:1259:31
    at Array.some (<anonymous>)
    at mergeProps (dev.js:1259:15)
    at info.jsx:151:61
    at Array.map (<anonymous>)
    at info.jsx:151:41
    at Object.fn (dev.js:212:58)
    at runComputation (dev.js:694:22)
    at updateComputation (dev.js:677:3)
    at runTop (dev.js:770:7)
```
info.jsx:151
```jsx
<div>{issues().map((o, i) => <Issue {...o} index={i} />)}</div>
```
issues is a signal array of objects.

### Steps to Reproduce the Bug or Issue
```jsx
const [issues, setIssues] = createSignal([{checkNo: 0, description: ''}])

const Component = () => (
  <div>{issues().map((o, i) => <Issue {...o} index={i} />)}</div>
)
```

### Platform

- OS: macOS 13.0.1
- Browser: Opera GX LVL4 (core: 92.0.4561.71) (arm64)
- Version: 1.5.1

**Comment by atk** [comment]
Cannot reproduce: https://playground.solidjs.com/anonymous/cd375ce3-9d7a-4bf3-9338-8f165697f3df

**Comment by ryansolid** [comment]
Can we get a reproduction?

**Comment by otonashixav** [comment]
I can reproduce the error, though not with the given code: https://playground.solidjs.com/anonymous/77bf2abe-b2ca-454b-bcb8-60d4f7a3c4be

```
​ Uncaught TypeError: Cannot use 'in' operator to search for 'Symbol(solid-proxy)' in 10
    at mergeProps (esm.sh/v99/solid-js@1.6.5/es2022/solid-js.development.js:1369:36)
    at 1622d192-d6c7-489d-b9e9-0b3d2cb3777d:15:56
    at esm.sh/v99/solid-js@1.6.5/es2022/web.development.js:165:53
    at updateFn (esm.sh/v99/solid-js@1.6.5/es2022/solid-js.development.js:172:14)
    at runUpdates (esm.sh/v99/solid-js@1.6.5/es2022/solid-js.development.js:868:17)
    at createRoot (esm.sh/v99/solid-js@1.6.5/es2022/solid-js.development.js:181:12)
    at render (esm.sh/v99/solid-js@1.6.5/es2022/web.development.js:163:3)
    at 1622d192-d6c7-489d-b9e9-0b3d2cb3777d:15:18
```

Which leads me to believe that `10` made it into `issues` somehow.

**Comment by ryansolid** [comment]
Yeah this seems the most likely. That they are attempting to spread a number. We could check for this I suppose but it still won't result in their desired outcome as it would just pass no props. I wonder if this is like a result of trying to call `.push` on an array and setting it with the new length or something.
