### ISSUE TITLE
Got error when trying to use node global variable at server side: "You probably are using a variable defined in a closure in your server function"

### ISSUE THREAD

**Issue by thanh-vo-opun-ai** [solidjs/solid#1431]
### Describe the bug

I got error when trying to use node global variable at server side.
I tried dynamic import on server side but the function is still "leaked" in to client.

This is the error content:
----
__filename is not defined You probably are using a variable defined in a closure in your server function.

Clear errors and retry
ReferenceError: __filename is not defined
    at __vite_ssr_exports__.default (/src/api/readFile.ts:6:60)
    at Object.$serverHandler0 (/src/routes/about.tsx?data:22:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async execute (/node_modules/.pnpm/solid-start@0.2.7_fj32xntqjaiayu4humqtymo7zu/node_modules/solid-start/server/server-functions/server.ts:201:17)
----

### Your Example Website or App

https://stackblitz.com/edit/github-lagvil-q2uwyc

### Steps to Reproduce the Bug or Issue

This is the code I added to default starter project with server side:

/src/api/readFile.ts
```ts
import fs from "fs";

export default function () {
  return String(fs.readFileSync(__filename));
}
```

/src/routes/about.tsx
```tsx
import { createResource } from "solid-js";
import { useRouteData, RouteDataArgs } from "solid-start";
import { isServer } from "solid-js/web";
import server$ from "solid-start/server";

export async function fetchAPI(path: string) {
  if (isServer) {
    return server$(async () => {
      const readFile = await import("../api/readFile");
      return readFile.default();
    })();
  }
  return "";
}

export function routeData({ params }: RouteDataArgs) {
  const [data] = createResource<string, string>(() => ``, fetchAPI);
  console.log(data);
  return data;
}

export default function About() {
  const data = useRouteData<typeof routeData>();
  console.log(data);
  return (
    <div class="wrapper">
      <h1>Hello</h1>
      <div>{data()}</div>
    </div>
  );
}
```

### Expected behavior

It should not show error of node global variable in client
Or the dynamic import should not import server code to client

### Platform

- OS: macOS
- Browser: Chrome
- Version: latest

**Comment by thanh-vo-opun-ai** [comment]
I tried to use node global variable in nextjs, and it worked
https://github.com/thanh-vo-opun-ai/fs_solidjs_nextjs/blob/main/nextjs-app/pages/index.tsx

But failed to migrate this approach to solidjs

**Comment by thanh-vo-opun-ai** [comment]
I also tried  

```ts
import { fileURLToPath } from "url"; 

const fileName : string = fileURLToPath(import.meta.url) 
```

as an alternative to __filename but it does not result in desired value

**Comment by thanh-vo-opun-ai** [comment]
Close this issue because it relate to vote
