### ISSUE TITLE
1.6.7 - Type error in doShell with renderToStream

### ISSUE THREAD

**Issue by jchatard** [solidjs/solid#1461]
### Describe the bug

I just upgraded my Solid Start app to 1.6.7 (that's the only package change).
I'm using `renderToStream`.

Using `renderAsync`makes the bug go away.

 it crashes on most pages with this error:

```
An unhandled error occured: TypeError: Cannot read properties of undefined (reading 'error')
    at doShell (/Users/jchatard/Documents/foo/front-solidjs/node_modules/.pnpm/solid-js@1.6.7/node_modules/solid-js/web/dist/server.cjs:410:79)
    at /Users/jchatard/Documents/foo/front-solidjs/node_modules/.pnpm/solid-js@1.6.7/node_modules/solid-js/web/dist/server.cjs:449:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

```js
function doShell() {
    solidJs.sharedConfig.context = context;
    context.noHydrate = true;
    html = injectAssets(context.assets, html);
    for (const key in context.resources) {
                                                                          \/ --> happening here
      if (!("data" in context.resources[key] || context.resources[key].ref[0].error)) pushTask(`_$HY.init("${key}")`);
    }
    for (const key of registry.keys()) pushTask(`_$HY.init("${key}")`);
    if (tasks.length) html = injectScripts(html, tasks, nonce);
    buffer.write(html);
    tasks = "";
    scheduled = false;
    onCompleteShell && onCompleteShell({
      write(v) {
        !completed && buffer.write(v);
      }
    });
  }
```

I don't really know how to track down this issue.

### Your Example Website or App

https://can-make-reproduction-at-the-moment.com

### Steps to Reproduce the Bug or Issue

The error occurs in dev mode and production mode as well. This crashes the vite server instantly.

### Expected behavior

The server does not crash and works the same regardless of using `renderAsync` or `renderToStream`.

### Screenshots or Videos

![Capture_d’écran_2023-01-04_à_21_10_52](https://user-images.githubusercontent.com/6790/210645825-aa285a67-9f98-47da-bf00-33a149dedb45.jpg)

### Platform

- OS: macOS

Content of package.json, but the app as many deps, so....

```json
{
  "name": "front-solidjs",
  "scripts": {
    "dev": "solid-start dev",
    "build": "npm run partytown  && solid-start build",
    "start": "solid-start start",
    "partytown": "partytown copylib public/~partytown",
    "test": "vitest",
    "coverage": "vitest run --coverage",
    "testui": "vitest --ui",
    "webstorm-integration": "vitest --watch --reporter=dot --reporter=json --outputFile=.vitest-result.json"
  },
  "type": "module",
  "pnpm": {
    "overrides": {
      "@solid-primitives/props": "3.0.1",
      "vite-plugin-solid": "2.5.0"
    },
    "patchedDependencies": {
      "@solid-primitives/script-loader@1.1.2": "patches/@solid-primitives__script-loader@1.1.2.patch",
      "@solidjs/router@0.6.0": "patches/@solidjs__router@0.6.0.patch"
    }
  },
  "devDependencies": {
    "@solidjs/meta": "^0.28.2",
    "@solidjs/router": "^0.6.0",
    "@solidjs/testing-library": "^0.5.1",
    "@testing-library/jest-dom": "^5.16.5",
    "@types/google.maps": "^3.51.0",
    "@types/intl-tel-input": "^17.0.6",
    "@types/leaflet": "^1.9.0",
    "@types/mapbox": "^1.6.42",
    "@types/testing-library__jest-dom": "^5.14.5",
    "@vitest/coverage-c8": "^0.26.3",
    "@vitest/ui": "^0.26.3",
    "autoprefixer": "^10.4.13",
    "jsdom": "^20.0.3",
    "postcss": "^8.4.20",
    "postcss-mixins": "^9.0.4",
    "postcss-nesting": "^10.2.0",
    "postcss-preset-env": "^7.8.3",
    "prettier": "2.8.1",
    "solid-js": "1.6.7",
    "solid-start": "0.2.10",
    "solid-start-node": "0.2.10",
    "solid-testing-library": "0.5.0",
    "solid-toast": "^0.4.0",
    "stylelint": "^14.16.1",
    "stylelint-config-prettier": "^9.0.4",
    "stylelint-config-standard": "^29.0.0",
    "typescript": "^4.9.4",
    "undici": "^5.14.0",
    "vanillajs-datepicker": "^1.2.0",
    "vite": "^3.2.5",
    "vite-plugin-solid-svg": "^0.6.0",
    "vitest": "^0.26.3",
    "xss": "^1.0.14"
  },
  "engines": {
    "node": ">=18"
  },
  "dependencies": {
    "@builder.io/partytown": "^0.7.3",
    "@felte/reporter-solid": "^1.2.4",
    "@felte/solid": "^1.2.6",
    "@felte/validator-zod": "^1.0.12",
    "@glidejs/glide": "^3.6.0",
    "@solid-aria/overlays": "^0.1.3",
    "@solid-primitives/resize-observer": "^2.0.7",
    "@solid-primitives/scheduled": "^1.2.0",
    "@solid-primitives/script-loader": "^1.1.2",
    "@solid-primitives/storage": "^1.3.3",
    "@tanstack/solid-query": "^4.20.9",
    "axios": "^1.2.2",
    "hashids": "^2.2.10",
    "imask": "^6.4.3",
    "intl-tel-input": "^17.0.19",
    "ioredis": "^5.2.4",
    "solid-collapse": "^1.1.0",
    "zod": "^3.20.2"
  }
}

```

**Comment by ryansolid** [comment]
Yeah.. my bad. I used the same data structure to dedupe lazy and I didn't realize I had references in DOM Expressions like that.
