### ISSUE TITLE
v1.6.13: on astrojs: r is not defined

### ISSUE THREAD

**Issue by btakita** [solidjs/solid#1613]
### Describe the bug

See https://github.com/withastro/astro/issues/6501

See https://github.com/ddiu8081/chatgpt-demo/issues/206

I am also getting this issue with solid-js 1.6.13 on astro. I created this issue here in case it is a problem w/ solid-js.

### Your Example Website or App

https://github.com/withastro/astro/issues/6501

### Steps to Reproduce the Bug or Issue

Create an astrojs with solid-js integration.

`npm run dev`

Open the home page.

### Expected behavior

No error

### Screenshots or Videos

```
(node:293403) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
  🚀  astro  v2.1.2 started in 42ms

  ┃ Local    http://localhost:4009/
  ┃ Network  use --host to expose

 error   r is not defined
  File:
    /home/brian/work/portfoliome/censible-core/apps/mi-www.site/@fs/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/solid-js@1.6.13/node_modules/solid-js/web/dist/server.js:297:5
  Stacktrace:
ReferenceError: r is not defined
    at eval (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/solid-js@1.6.13/node_modules/solid-js/web/dist/server.js:297:5)
    at Module.createRoot (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/solid-js@1.6.13/node_modules/solid-js/dist/server.js:49:14)
    at Module.renderToString (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/solid-js@1.6.13/node_modules/solid-js/web/dist/server.js:294:36)
    at Object.renderToStaticMarkup (@astrojs/solid-js/server.js:16:38)
    at renderFrameworkComponent (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/astro@2.1.2/node_modules/astro/dist/runtime/server/render/component.js:178:66)
```

### Platform

- OS: all
- Browser: all
- Version: 1.6.13

**Comment by lxsmnsyc** [comment]
yeah probably a typo: <https://github.com/ryansolid/dom-expressions/blob/main/packages/dom-expressions/src/server.js#L26-L29>
