### ISSUE TITLE
>= 1.8.2 - Cannot read properties of null (reading 'nextSibling')

### ISSUE THREAD

**Issue by jchatard** [solidjs/solid#1955]
### Describe the bug

Hi, the issue happens on average every 6 to 10 page loads.

I'm was updating Solid & Solid-Start versions.

From:

    "solid-js": "^1.8.1",  // I don't seem to have this issue, I tried really hard to reproduce, but with no success
    "solid-start": "0.3.6",
    "solid-start-node": "0.3.6",

To:

    "solid-js": "^1.8.5", // Bug appears on every 6 to 10 page loads
    "solid-start": "0.3.10",
    "solid-start-node": "0.3.10",

Toggling `{ omitNestedClosingTags: true }` to `false` doesn't seem to have any incidence.
I user server rendering, but not streaming.

As it's not on every page load, it's hard to reproduce:

Cannot read properties of null (reading 'nextSibling')

    Clear errors and retry
    TypeError: Cannot read properties of null (reading 'nextSibling')
        at https://dev.local-site.fr/assets/ContactBlock-4a08b4fc.js:1:6287
        at c1 (https://dev.local-site.fr/assets/ContactBlock-4a08b4fc.js:1:7382)
        at https://dev.local-site.fr/assets/entry-client-9df490a6.js:1:11547
        at qe (https://dev.local-site.fr/assets/entry-client-9df490a6.js:1:3108)
        at d (https://dev.local-site.fr/assets/entry-client-9df490a6.js:1:11540)
        at https://dev.local-site.fr/assets/_id_-99e57ad2.js:4:176
        at Vt (https://dev.local-site.fr/assets/_id_-99e57ad2.js:4:226)
        at https://dev.local-site.fr/assets/entry-client-9df490a6.js:1:11547
        at qe (https://dev.local-site.fr/assets/entry-client-9df490a6.js:1:3142)
        at d (https://dev.local-site.fr/assets/entry-client-9df490a6.js:1:11540) 

I saw previous similar issues, I don't know if they are the same:

- https://github.com/solidjs/solid-start/issues/820
- https://github.com/solidjs/solid/issues/1697#issuecomment-1568611382
- https://github.com/solidjs/solid/issues/1917

### Your Example Website or App

https://no-repro-yet.sorry

### Steps to Reproduce the Bug or Issue

I tried to re-create the bug with a minimal bare solid start project, but as of now, I can't seem to succeed to reproduce it.

The error happens in this component, which doesn't have anything fancy:

```tsx
import type { Settings } from "~/types/common";

import "./ContactBlock.css";
import IconCall from "~/img/icons/call.svg";
import IconFace from "~/img/icons/face.svg";
import IconEdit from "~/img/icons/edit.svg";
import GreenNumber from "~/img/icons/green-number.svg";
import { useEventsContext } from "~/contexts/EventsContext";
import imgProxy from "~/utils/imgproxy";

export default function ContactBlock(props: { settings?: Settings }) {
  const [, { sendClick }] = useEventsContext();

  return (
    <>
      <section class="page-contact-block" data-test="block-contact">
        <picture class="background">
          <source
            media="(max-width: 480px)"
            srcset={imgProxy(
              "/images/bgs/findus-geography-bg-2023.jpg",
              "size:480:415/resizing_type:fill",
            )}
          />
          <source
            media="(max-width: 768px)"
            srcset={imgProxy(
              "/images/bgs/findus-geography-bg-2023.jpg",
              "size:768:415/resizing_type:fill",
            )}
          />
          <source
            media="(min-width: 769px)"
            srcset={imgProxy(
              "/images/bgs/findus-geography-bg-2023.jpg",
              "size:1200:415/resizing_type:fill",
            )}
          />
          <img
            src={imgProxy(
              "/images/bgs/findus-geography-bg-2023.jpg",
              "size:480:415/resizing_type:fill",
            )}
            alt=""
            loading="lazy"
            width="360"
            height="167"
          />
        </picture>

        <div class="content-part">
          <div class="contact-items">
            <div class="item" data-test="block-phone">
              <div class="icon">
                <i aria-hidden="true" class="kb-icon">
                  <IconCall />
                </i>
              </div>
              <div class="text">
                <h3 class="phone">
                  <a
                    href={`tel:${props.settings?.phone_number}`}
                    onClick={() => sendClick("phone", "in-page")}
                  >
                    <GreenNumber />
                    {props.settings?.phone_number}
                  </a>
                </h3>
                <p>
                  Pour connaître l'espace de vente le plus proche de chez vous.
                </p>
              </div>
            </div>
            <div class="item" data-test="block-advisor">
              <div class="icon">
                <i aria-hidden="true" class="kb-icon">
                  <IconFace />
                </i>
              </div>
              <div class="text">
                <h3>Un conseiller chez vous</h3>
                <p>
                  Nos conseillers se déplacent sur rendez-vous, sur le lieu de
                  votre choix.
                </p>
              </div>
            </div>
            <div class="item" data-test="block-newsroom">
              <div class="icon">
                <i aria-hidden="true" class="kb-icon">
                  <IconEdit />
                </i>
              </div>
              <div class="text">
                <h3>Journaliste ?</h3>
                <p>
                  Nous vous proposons un{" "}
                  <a
                    href="https://newsroom.xxxx.fr/"
                    rel="noopener noreferrer"
                  >
                    espace presse dédié
                  </a>
                  .
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
```

And is compiled to:

```js
import {g as _, d as M, I as l, s, t as $, ap as U, X as S, ae as X, p as w, q as r, c as g, ay as D, ar as K, _ as L} from "./entry-client-9df490a6.js";
import {I as O} from "./edit-9d58ddd6.js";
const Q = $('<picture class=main-visual data-test=main-image><source media="(min-width: 1366px)"><source media="(min-width: 1024px) and (max-width: 1365px)"><img fetchpriority=high alt=""loading=lazy width=1024 height=576>');
function i1(c) {
    return (()=>{
        const t = _(Q)
          , n = t.firstChild
          , v = n.nextSibling
          , d = v.nextSibling;
        return M(i=>{
            const a = l(c.filename, "size:1920:1080/resizing_type:fill")
              , o = l(c.filename, "size:1366:768/resizing_type:fill")
              , m = l(c.filename, "size:1024:576/resizing_type:fill");
            return a !== i._v$ && s(n, "srcset", i._v$ = a),
            o !== i._v$2 && s(v, "srcset", i._v$2 = o),
            m !== i._v$3 && s(d, "src", i._v$3 = m),
            i
        }
        , {
            _v$: void 0,
            _v$2: void 0,
            _v$3: void 0
        }),
        t
    }
    )()
}
const T = $('<svg xmlns=http://www.w3.org/2000/svg style="enable-background:new 0 0 465 57"viewBox="0 0 465 57"><path d="M463.4 3v50.9H1.6V3h461.8m1.5-1.5H.1v53.9H465l-.1-53.9z"></path><path d="M391.1 19.9v.6c0 1 .5 1.1 1 1.1 1.2 0 2.4-.9 2.4-.9v-2.1l-2.5.2c-.8-.1-.9.5-.9 1.1zM404.1 14.7c-1 0-1.9.3-2.5.7v5.8c.7.3 1.5.4 2.5.4.9 0 1.4-.6 1.4-3.5 0-2.6-.5-3.4-1.4-3.4zM373.2 17.6c-1.1 1-.9 1.9-.3 2.7.5.7 1.5 1.2 2.4.3l1-1.1-2-2.9-1.1 1zM317.4 16.2c0-1.5-.2-1.7-1.5-1.7-1.5 0-2 .1-2 2.6h2.6c.5-.1.9-.4.9-.9zM302.1 38.3c0 1.1.3 1.8 1.3 1.8h1.1c1.1 0 1.4-.8 1.3-1.8 0-1.2-.4-1.7-1.4-1.7h-1.1c-.9 0-1.2.8-1.2 1.7zM303.4 49.3h1.6c1 0 1.1-.5 1.1-1.2v-.9c0-.7-.2-1.1-1-1.1H303c-.4 0-.8-.1-.8-.1v2c0 1.2.6 1.3 1.2 1.3z"></path><path d="M278.4.1v14.1l14.3 14.3-14.3 14.3v14.1h172.3V.1H278.4zm81 12c3 0 4.5.4 4.5 4.3 0 2.1-1 2.9-2.9 2.9h-3.3c0 2.1.7 2.2 2.2 2.2 1.6 0 2.4 0 3.9-.2v2.1c-1.5.6-3.7.6-5.4.6-2.7 0-3.5-1.7-3.5-6-.1-5.1 1.1-5.9 4.5-5.9zm-18.5-3.6c0-.3.2-.6.5-.6h2.1c.3 0 .4.2.4.6v2c0 .3-.2.5-.4.5h-2.1c-.3 0-.5-.2-.5-.5v-2zm2.9 3.7v11.7H341V12.2h2.8zm-22.2 0h2.3l.4 1.5c.7-.8 1.7-1.6 3-1.6.5 0 .9 0 1.2.1v3c-.3 0-.9-.1-1.5-.1-1.1 0-2 .2-2.7 1.3v7.4h-2.7V12.2zm-6-.1c3 0 4.5.4 4.5 4.3 0 2.1-1 2.9-2.9 2.9H314c0 2.1.7 2.2 2.2 2.2 1.6 0 2.4 0 3.9-.2v2.1c-1.5.6-3.7.6-5.4.6-2.7 0-3.5-1.7-3.5-6-.2-5.1 1.2-5.9 4.4-5.9zm-6.2 23.8-1.2.4c.2.5.4.9.4 2.3 0 1.7-.6 3.9-3.6 3.9h-2.4c-.3 0-.8 0-.8.5s.4.6.8.6h3.2c1.9 0 3.1 1.1 3.1 3.5v1.3c0 1.7-.7 3.4-3.3 3.4h-3c-1.9 0-3.3-1.1-3.3-3.4v-1.5l.9-1.1c-.6-.3-1-1.1-1-2.3 0-.9.4-1.8 1.2-2.1-.9-.6-1.2-2.1-1.2-3.2 0-2.8 1.3-4.2 3.6-4.2h6.4v1.9h.2zm.2-16.2c0 3.7-2.1 4.3-4 4.3-2.5 0-4.1-.2-5.6-.7v-2.4c.8.1 3.2.2 5 .2.8 0 1.8-.2 1.8-1.4v-.9c0-.9-.2-1.5-1.3-1.5h-2.2c-3.5 0-3.7-2.9-3.7-4.3v-1.4c0-3.2 1.7-4.1 3.9-4.2 2.1 0 4.5.3 5.6.6v2.4c-1.3-.1-4.1-.2-4.8-.2-1.2 0-1.9.1-1.9 1.6v.8c0 1.3.4 1.6 1.6 1.6h2.3c2.8 0 3.4 2.5 3.4 4.3l-.1 1.2zm8 17.4c-.3 0-.9-.1-1.5-.1-1.1 0-2 .2-2.7 1.3v7.4h-2.8V34.2h2.3l.4 1.5c.7-.8 1.7-1.6 3-1.6.5 0 .9 0 1.2.1v2.9h.1zm9.9 8.7h-2.2l-.6-1.3c-.1.3-1.6 1.5-3.2 1.4-2-.1-3-1.6-3-3.1v-1.1c0-1.7.8-3.2 3.1-3.2h3.1v-.7c0-1.2-.5-1.4-1.4-1.4s-3.6.2-4.4.3v-1.9c1.4-.6 2.8-.8 4.8-.8 2.3 0 3.8.9 3.8 3.8v8zm7.9-9.3H333v4.7c0 1.7.4 2.1.9 2.3 0 0 1.2.5 1.3.5v1.9h-2.4c-1.6 0-2.6-1.1-2.6-4.2v-5.2h-1.7v-1.7l1.7-.6.5-3.3h2.3v3.3h2.4v2.3zm-2.5-12.7-3.7-11.7h3l2.3 8.1 2.4-8.1h3l-3.8 11.7h-3.2zm13 22h-2.2l-.5-1.2c-1 .7-1.7 1.4-3.3 1.4-2.4 0-3.1-1.9-3.1-4.1v-7.8h2.8V42c0 1.2.5 1.6 1.2 1.6 1.1 0 1.7-.3 2.5-1v-8.4h2.8v11.6h-.2zm-.5-27.8c0-4.8 1.4-5.9 3.5-5.9 1 0 3.1.1 4.8.7v1.9s-1.9-.1-3.7-.1c-1.3 0-1.9.1-1.9 3.5 0 3 .5 3.4 1.9 3.4 1.8 0 3.8-.2 3.8-.2v1.9c-1.5.9-3.3.7-5 .7-1.9 0-3.4-1.1-3.4-5.9zm5 27.8h-2.8V34.2h2.8v11.6zm0-13.4c0 .3-.2.5-.4.5h-2.1c-.3 0-.5-.2-.5-.5v-2c0-.3.2-.5.5-.5h2.1c.3 0 .4.2.4.5v2zm8 4.1H356v4.7c0 1.7.4 2.1.9 2.3 0 0 1.2.5 1.3.5v1.9h-2.4c-1.6 0-2.6-1.1-2.6-4.2v-5.2h-1.7v-1.7l1.7-.6.5-3.3h2.3v3.3h2.4v2.3zm9.8 6.4c0 2.4-1.3 3.1-2.6 3.1-2 0-5.1-.1-5.9-.6v-1.9h5c.2 0 .7 0 .7-.7v-.5c0-.5-.1-.8-.7-.8h-2.5c-1.9 0-3-.9-3-3.1v-1c0-1.8.7-3.1 2.7-3.1s4.8.1 5.6.6v1.9h-4.8c-.7 0-.8.2-.8.8v.5c0 .7.3.8.8.8h2.5c2 0 2.8 1.3 2.8 3v1h.2zm11-19.1-1.4-2.1-1.3 1.3c-1.4 1.3-4.4 1.4-5.9-1-1.4-2.2-.8-4.7.9-6.3l1.4-1.3-1-1.6c-1.6-2.4 0-4.7 1.6-5 2.4-.4 4.1.1 5.5.4v2.2h-3.3c-1.5 0-1.7.7-.7 2.2l3.3 5.1 2.4-2.5 1 1.3-1.2 2.4-.7 1 2.7 4h-3.3v-.1zm18.2 0h-2.2l-.6-1.3c-.1.3-1.6 1.5-3.2 1.4-2-.1-3-1.6-3-3.1v-1.1c0-1.7.8-3.2 3.1-3.2h3.1v-.7c0-1.2-.5-1.4-1.4-1.4s-3.6.2-4.4.3v-1.9c1.4-.6 2.8-.8 4.8-.8 2.3 0 3.8.9 3.8 3.8v8zm7.5.2c-.9 0-2.2-.3-3.2-.8v6.5h-2.8V12.2h2.3l.5 1.2c.7-.6 1.9-1.3 3.2-1.3 2.6 0 3.4 2.4 3.4 5.9.1 3.3-.4 6-3.4 6zm11 0c-.9 0-2.2-.3-3.2-.8v6.5h-2.8V12.2h2.3l.5 1.2c.7-.6 1.9-1.3 3.2-1.3 2.6 0 3.4 2.4 3.4 5.9.1 3.3-.4 6-3.4 6zm10-2.5c1.6 0 2.4 0 3.9-.2v2.1c-1.5.6-3.7.6-5.4.6-2.7 0-3.5-1.7-3.5-6 0-5 1.3-5.9 4.6-5.9 3 0 4.5.4 4.5 4.3 0 2.1-1 2.9-2.9 2.9h-3.3c-.3 2.1.6 2.2 2.1 2.2zm10.5 2.3h-2.3c-1.7 0-2.7-1.1-2.7-4.2v-13h2.8v12.6c0 1.7.4 2.1.9 2.3 0 0 1.2.5 1.3.5v1.8z"></path><path d="M361 16.2c0-1.5-.2-1.7-1.5-1.7-1.5 0-2 .1-2 2.6h2.6c.7-.1.9-.4.9-.9zM425.5 14.4c-1.5 0-2 .1-2 2.6h2.6c.6 0 .9-.3.9-.9.1-1.4-.1-1.7-1.5-1.7zM321.4 41.9v.6c0 1 .5 1.1 1 1.1 1.2 0 2.4-.9 2.4-.9v-2.1l-2.5.2c-.9-.1-.9.5-.9 1.1zM415.2 14.7c-1 0-1.9.3-2.5.7v5.8c.7.3 1.5.4 2.5.4.9 0 1.4-.6 1.4-3.5-.1-2.6-.6-3.4-1.4-3.4z">')
  , W = (c={})=>(()=>{
    const t = _(T);
    return U(t, c, !0, !0),
    S(),
    t
}
)()
  , Y = $(`<section class=page-contact-block data-test=block-contact><picture class=background><source media="(max-width: 480px)"><source media="(max-width: 768px)"><source media="(min-width: 769px)"><img alt=""loading=lazy width=360 height=167></picture><div class=content-part><div class=contact-items><div class=item data-test=block-phone><div class=icon><i aria-hidden=true class=kb-icon></i></div><div class=text><h3 class=phone><a><!$><!/><!$><!/></a></h3><p>Pour connaître l'espace de vente le plus proche de chez vous.</p></div></div><div class=item data-test=block-advisor><div class=icon><i aria-hidden=true class=kb-icon></i></div><div class=text><h3>Un conseiller chez vous</h3><p>Nos conseillers se déplacent sur rendez-vous, sur le lieu de votre choix.</p></div></div><div class=item data-test=block-newsroom><div class=icon><i aria-hidden=true class=kb-icon></i></div><div class=text><h3>Journaliste ?</h3><p>Nous vous proposons un <a href=https://newsroom.xxxx.fr/ rel="noopener noreferrer">espace presse dédié</a>.`);
function c1(c) {
    const [,{sendClick: t}] = X();
    return (()=>{
        const n = _(Y)
          , v = n.firstChild
          , d = v.firstChild
          , i = d.nextSibling // <-------- crashing here
          , a = i.nextSibling
          , o = a.nextSibling
          , m = v.nextSibling
          , V = m.firstChild
          , u = V.firstChild
          , z = u.firstChild
          , H = z.firstChild
          , E = z.nextSibling
          , I = E.firstChild
          , h = I.firstChild
          , N = h.firstChild
          , [f,j] = w(N.nextSibling)
          , B = f.nextSibling
          , [P,q] = w(B.nextSibling)
          , p = u.nextSibling
          , A = p.firstChild
          , F = A.firstChild
          , G = p.nextSibling
          , J = G.firstChild
          , R = J.firstChild;
        return r(H, g(D, {})),
        h.$$click = ()=>t("phone", "in-page"),
        r(h, g(W, {}), f, j),
        r(h, ()=>c.settings?.phone_number, P, q),
        r(F, g(K, {})),
        r(R, g(O, {})),
        M(e=>{
            const b = l("/images/bgs/findus-geography-bg-2023.jpg", "size:480:415/resizing_type:fill")
              , x = l("/images/bgs/findus-geography-bg-2023.jpg", "size:768:415/resizing_type:fill")
              , C = l("/images/bgs/findus-geography-bg-2023.jpg", "size:1200:415/resizing_type:fill")
              , y = l("/images/bgs/findus-geography-bg-2023.jpg", "size:480:415/resizing_type:fill")
              , k = `tel:${c.settings?.phone_number}`;
            return b !== e._v$ && s(d, "srcset", e._v$ = b),
            x !== e._v$2 && s(i, "srcset", e._v$2 = x),
            C !== e._v$3 && s(a, "srcset", e._v$3 = C),
            y !== e._v$4 && s(o, "src", e._v$4 = y),
            k !== e._v$5 && s(h, "href", e._v$5 = k),
            e
        }
        , {
            _v$: void 0,
            _v$2: void 0,
            _v$3: void 0,
            _v$4: void 0,
            _v$5: void 0
        }),
        S(),
        n
    }
    )()
}
L(["click"]);
export {c1 as C, i1 as M};

```

I'm wondering if this is related to the `<source>` which is self closing.

### Expected behavior

The component renders on evey request.

### Screenshots or Videos

![next](https://github.com/solidjs/solid/assets/6790/2b4cad69-6c91-4074-b6c0-3a747cf3061c)

### Platform

- OS: macOS
- Browser: Chrome 119, Firefox 118

### Additional context

I'll will try to work more on a reproduction later. Sorry for not providing a repro...

**Comment by jchatard** [comment]
Another experiment shows that only updating Solid, not Start, I'm  able to reproduce the bug.
So that would mean, Start is not involved.

From:

```
"solid-js": "^1.8.1",  // I don't seem to have this issue, I tried really hard to reproduce, but with no success
"solid-start": "0.3.6",
"solid-start-node": "0.3.6",
```

To:

```
"solid-js": "^1.8.5", // Bug appears on every 6 to 10 page loads
"solid-start": "0.3.6",
"solid-start-node": "0.3.6",
```

**Comment by jchatard** [comment]
Certainly! Here's a revised version of your text for clarity:

"After conducting further tests, I've discovered that the issue begins with version 1.8.2. This observation is made in the absence of any Solid-Start updates.

I methodically tested versions ranging from 1.8.1 through to 1.8.5. The errors started occurring from version 1.8.2 onwards."

**Comment by jchatard** [comment]
I could narrow down to a resource which was lacking a `<Suspense>`, so I could upgrade to latest Solid 1.8.5, run all tests and it's working.

But what remains strange to me is why did this work _before_ the upgrade...

So I was fetching a resource at the routeData level. And deep down the tree of components the hydration failed from time to time, but only when the resource was cached (so very fast to resolve). It's an in-house solution, a Redis cache wrapper around a fetch call.

So if I encounter the same issue later, `<Suspense>`, `<Suspense>`, `<Suspense>`...

So closing, for the noise.
