### ISSUE TITLE
[solid-js/html] Using `<Show>` inside `html` causes `Cannot read properties of undefined (reading 'keyed')`

### ISSUE THREAD

**Issue by trusktr** [solidjs/solid#2032]
### Describe the bug

I have an `html` template containing this:

```js
html`
	<${Show} when=${() => !this.isMobile}>
		<lume-element3d ref=${e => (this.circle = e)} />
	</${Show}>
`
```

and it causes a runtime error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'keyed')
    at Show (dev.js:1497:23)
    at Object.fn (web.js:239:58)
    at runComputation (dev.js:708:22)
    at updateComputation (dev.js:690:3)
    at createRenderEffect (dev.js:219:75)
    at Object.insert (web.js:239:3)
    at HTMLTemplateElement.eval [as create] (eval at functionBuilder (html.js:192:34), <anonymous>:83:3)
    at html (html.js:551:25)
    at ElementDecorator.template (App.ts:205:23)
    at web.js:114:53
```

### Your Example Website or App

https://playground.solidjs.com/anonymous/34160a2f-caf1-4230-98dd-eb6f10500fb4

### Steps to Reproduce the Bug or Issue

1. Run the [playground example](https://playground.solidjs.com/anonymous/34160a2f-caf1-4230-98dd-eb6f10500fb4)
2. see console

### Expected behavior

For `Show` to work.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

In `solid-js/web`, in the `insert` function,

```js
function insert(parent, accessor, marker, initial) {
  if (marker !== undefined && !initial) initial = [];
  if (typeof accessor !== "function") return insertExpression(parent, accessor, initial, marker);
  createRenderEffect(current => insertExpression(parent, accessor(), current, marker), initial);
}
```

`accessor()` is being called without arguments. `accessor` happens to be a reference to the `Show` function.

The `Show` function tried to read properties from a `props` argument:

```js
function Show(props) {
  const keyed = props.keyed; // ERROR: Cannot read properties of undefined (reading 'keyed')
  ...
}
```

**Comment by ryansolid** [comment]
We won't be changing Solid's official Tag Template solution in V1 as that would be breaking. But 2.0 has a new rewritten system that addresses many of the issues. This issue has been confirmed working on the 2.0 branch. Since it will never get resolution in 1.x, I'm closing as fixed.

Thank you for reporting the issue and helping us make Solid better than ever.
