### ISSUE TITLE
`npm run dev` is broken with solid-js@1.2.6

### ISSUE THREAD

**Issue by bgoscinski** [solidjs/solid#760]
**Describe the bug**
I bootstrapped new project using solid-start but when trying to start it I get the error originating from solid-js/dist/server.cjs

**To Reproduce**
Provide a code snippet and steps to reproduce the behavior:

1. `mkdir my-app`
2. `cd my-app`
3. `npm init solid@next`
4. `npm install`
5. make sure that only version 1.2.6 of solid-js is intalled: `npm ls solid-js`
6. `npm run dev -- --open`

**Expected behavior**
No error, example app runs correctly.

**Actual behavior**
```
/c/dev/my-app
$ npm run dev -- --open

> dev
> solid-start dev "--open"

Pre-bundling dependencies:
  solid-js
  solid-js/web
  solid-js/store
  solid-js/html
  solid-js/h
(this will be run only when your dependencies or config have changed)
http://localhost:3000
TypeError: Cannot read properties of undefined (reading 'id')
    at wrap (C:\dev\my-app\node_modules\solid-js\dist\server.cjs:385:37)
    at Proxy.createComponent (C:\dev\my-app\node_modules\solid-js\dist\server.cjs:229:10)
    at Object.element.component.element.element [as outlet] (/node_modules/solid-app-router/dist/routing.js:59:35)
    at Object.get children [as children] (c:/dev/my-app/node_modules/solid-app-router/dist/components.jsx:56:57)
    at C:\dev\my-app\node_modules\solid-js\dist\server.cjs:138:35
    at C:\dev\my-app\node_modules\solid-js\dist\server.cjs:106:43
    at createMemo (C:\dev\my-app\node_modules\solid-js\dist\server.cjs:54:13)
    at children (C:\dev\my-app\node_modules\solid-js\dist\server.cjs:106:10)
    at C:\dev\my-app\node_modules\solid-js\dist\server.cjs:138:14
    at createMemo (C:\dev\my-app\node_modules\solid-js\dist\server.cjs:54:13)
```

**Additional context**
Downgrading solid-js to 1.2.5 fixes the issue:
1. Make sure you're using npm that supports overrides: `npm i -g npm@^8.3.0`
2. Apply this change:
    ```diff
    diff --git a/package.json b/package.json
    index b7bd862..21928be 100644
    --- a/package.json
    +++ b/package.json
    @@ -8,7 +8,7 @@
       "type": "module",
       "devDependencies": {
         "solid-app-router": "^0.1.14",
    -    "solid-js": "^1.2.6",
    +    "solid-js": "1.2.5",
         "solid-meta": "^0.27.2",
         "solid-start": "next",
         "solid-start-node": "next",
    @@ -16,5 +16,8 @@
       },
       "engines": {
         "node": ">=12"
    +  },
    +  "overrides": {
    +    "solid-js": "1.2.5"
       }
     }
    ```
3. `rm -rf package-lock.json node_modules`
4. `npm install`
5. make sure that only version 1.2.5 of solid-js is intalled: `npm ls solid-js`
6. `npm run dev -- --open`
```
$ npm run dev -- --open

> dev
> solid-start dev "--open"

Pre-bundling dependencies:
  solid-js
  solid-js/web
  solid-js/store
  solid-js/html
  solid-js/h
(this will be run only when your dependencies or config have changed)
http://localhost:3000
You appear to have multiple instances of Solid. This can lead to unexpected behavior.
computations created outside a `createRoot` or `render` will never be disposed
computations created outside a `createRoot` or `render` will never be disposed
computations created outside a `createRoot` or `render` will never be disposed
computations created outside a `createRoot` or `render` will never be disposed
computations created outside a `createRoot` or `render` will never be disposed
computations created outside a `createRoot` or `render` will never be disposed
computations created outside a `createRoot` or `render` will never be disposed
```

**Comment by Brendan-csel** [comment]
Let me guess.  You're building on Windows?  Me too.

I've filed an [issue with Vite](https://github.com/vitejs/vite/issues/6080).

**Comment by ryansolid** [comment]
It's funny the change was specifically to handle something in Vite `2.7.x` which was resolving dev mode on the server rendering. Is it possible different deps are pulling in different versions. vite-plugin-solid has been particularly problematic. Also moving to SolidStart as this seems Solid Start related.
