### ISSUE TITLE
Suspense tests randomly fail

### ISSUE THREAD

**Issue by otonashixav** [solidjs/solid#761]
**Describe the bug**

This happens for me about half the time:
```sh
 FAIL  web/test/suspense.spec.tsx
  ● Console

    console.error
      Error: Uncaught [Error: expect(received).toBe(expected) // Object.is equality
      
      Expected: true
      Received: false]
          at reportException (C:\Users\Otonashi\solid\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:66:24)
          at Timeout.task [as _onTimeout] (C:\Users\Otonashi\solid\node_modules\jsdom\lib\jsdom\browser\Window.js:521:9)
          at listOnTimeout (node:internal/timers:557:17)
          at processTimers (node:internal/timers:500:7) JestAssertionError: expect(received).toBe(expected) // Object.is equality
      
      Expected: true
      Received: false
          at C:\Users\Otonashi\solid\packages\solid\web\test\suspense.spec.tsx:51:25
          at Timeout.task [as _onTimeout] (C:\Users\Otonashi\solid\node_modules\jsdom\lib\jsdom\browser\Window.js:516:19)
          at listOnTimeout (node:internal/timers:557:17)
          at processTimers (node:internal/timers:500:7) {
        matcherResult: {
          actual: false,
          expected: true,
          message: [Function (anonymous)],
          name: 'toBe',
          pass: false
        }
      }

      at VirtualConsole.<anonymous> (../../node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at reportException (../../node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:70:28)
      at Timeout.task [as _onTimeout] (../../node_modules/jsdom/lib/jsdom/browser/Window.js:521:9)

    console.error
      Error: Uncaught [Error: expect(received).toBe(expected) // Object.is equality
      
      Expected: "Hi, Jo.Hello Jo"
      Received: ""]
          at reportException (C:\Users\Otonashi\solid\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:66:24)
          at Timeout.task [as _onTimeout] (C:\Users\Otonashi\solid\node_modules\jsdom\lib\jsdom\browser\Window.js:521:9)
          at listOnTimeout (node:internal/timers:557:17)
          at processTimers (node:internal/timers:500:7) JestAssertionError: expect(received).toBe(expected) // Object.is equality
      
      Expected: "Hi, Jo.Hello Jo"
      Received: ""
          at C:\Users\Otonashi\solid\packages\solid\web\test\suspense.spec.tsx:54:29
          at Timeout.task [as _onTimeout] (C:\Users\Otonashi\solid\node_modules\jsdom\lib\jsdom\browser\Window.js:516:19)
          at listOnTimeout (node:internal/timers:557:17)
          at processTimers (node:internal/timers:500:7) {
        matcherResult: {
          actual: '',
          expected: 'Hi, Jo.Hello Jo',
          message: [Function (anonymous)],
          name: 'toBe',
          pass: false
        }
      }

      at VirtualConsole.<anonymous> (../../node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at reportException (../../node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:70:28)
      at Timeout.task [as _onTimeout] (../../node_modules/jsdom/lib/jsdom/browser/Window.js:521:9)

  ● Testing Suspense › Toggle with refresh transition

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      49 |     setTimeout(() => {
      50 |       expect(div.innerHTML).toBe("Hi, .Hello ");
    > 51 |       expect(pending()).toBe(true);
         |                         ^
      52 |     });
      53 |     setTimeout(() => {
      54 |       expect(div.innerHTML).toBe("Hi, Jo.Hello Jo");

      at web/test/suspense.spec.tsx:51:25
      at Timeout.task [as _onTimeout] (../../node_modules/jsdom/lib/jsdom/browser/Window.js:516:19)

  ● SuspenseList › revealOrder forwards

    expect(received).toBe(expected) // Object.is equality

    Expected: "Hi, Jo.Hello Jo"
    Received: ""

      52 |     });
      53 |     setTimeout(() => {
    > 54 |       expect(div.innerHTML).toBe("Hi, Jo.Hello Jo");
         |                             ^
      55 |       expect(pending()).toBe(false);
      56 |       expect(finished).toBe(true);
      57 |       done();

      at web/test/suspense.spec.tsx:54:29
      at Timeout.task [as _onTimeout] (../../node_modules/jsdom/lib/jsdom/browser/Window.js:516:19)

Summary of all failing tests
 FAIL  web/test/suspense.spec.tsx
  ● Testing Suspense › Toggle with refresh transition

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      49 |     setTimeout(() => {
      50 |       expect(div.innerHTML).toBe("Hi, .Hello ");
    > 51 |       expect(pending()).toBe(true);
         |                         ^
      52 |     });
      53 |     setTimeout(() => {
      54 |       expect(div.innerHTML).toBe("Hi, Jo.Hello Jo");

      at web/test/suspense.spec.tsx:51:25
      at Timeout.task [as _onTimeout] (../../node_modules/jsdom/lib/jsdom/browser/Window.js:516:19)

  ● SuspenseList › revealOrder forwards

    expect(received).toBe(expected) // Object.is equality

    Expected: "Hi, Jo.Hello Jo"
    Received: ""

      52 |     });
      53 |     setTimeout(() => {
    > 54 |       expect(div.innerHTML).toBe("Hi, Jo.Hello Jo");
         |                             ^
      55 |       expect(pending()).toBe(false);
      56 |       expect(finished).toBe(true);
      57 |       done();

      at web/test/suspense.spec.tsx:54:29
      at Timeout.task [as _onTimeout] (../../node_modules/jsdom/lib/jsdom/browser/Window.js:516:19)

Test Suites: 1 failed, 20 passed, 21 total
Tests:       2 failed, 316 passed, 318 total
Snapshots:   0 total
Time:        6.602 s
Ran all test suites.
```

**To Reproduce**
1. Run `npm test`
2. Maybe the test fails?
3. Rerun `npm test` until the test doesn't fail

**Expected behavior**
The behaviour should be deterministic. 

**Additional context**
Windows 10 Pro 21H1 Build 19043.1348
npm 8.1.1

**Comment by ryansolid** [comment]
Yeah.. we can't depend on the timer resolution I guess and probably varies on the machine. I'd be open to suggestions. I've been having these sort of issues trying to test a lot of the async stuff. I guess we need a setup where we can force the sequence. Almost like async generators. I'd be interested if anyone has experience here. Most of the time I'd just set sufficiently long timeouts but it's awkward when you have a sequence of several steps.

**Comment by benjamingr** [comment]
Why are you using "real" timers in the first place?
